name: Deploy to server
concurrency: deploy

on:
  workflow_run:
    workflows: [CI actions]
    branches: [main]
    types:
      - completed

  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Buid application
        run: yarn build

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/deploy.key
          chmod 600 ~/.ssh/deploy.key
          chmod 700 ~/.ssh
          cat >>~/.ssh/config <<END
          Host deploy
            HostName $SSH_HOST
            User $SSH_USER
            Port $SSH_PORT
            IdentityFile ~/.ssh/deploy.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOSTNAME }}
          SSH_PORT: ${{ secrets.SSH_PORT }}   
      
      - name: Upload files
        run: scp -r dist deploy:$DST_DIR
        env:
          DST_DIR: ${{ secrets.DESTINATION }}
     
      - name: Deployment completed
        run: echo 'Finished!'
